### ISSUE TITLE
[RFE] Allow `hauler` to pull `content` from authenticated registries

### ISSUE THREAD

**Issue by zackbradys** [hauler-dev/hauler#171]
**Is your feature request related to a problem? Please describe.**
* Yes, see below

**Describe the solution you'd like**
* Add functionality to `hauler` so users are able to authenticate to authenticated/private registries (like the carbide registry) before using other commands such as `hauler store sync` or `hauler store add` or `hauler store copy`.
* Possible implementation could be `hauler login` and then we could remove the flags from `hauler store copy`.

**Describe alternatives you've considered**
* Using other tools to authenticate such as `cosign login` or `docker login`

**Additional context**
*

**Comment by amartin120** [comment]
And to not confuse anyone looking at this, you can PULL from authenticated registries.  You just have to run a `docker/cosign login` first.  The idea behind the issue is having Hauler handle that for you just like it does for copying TO an authenticated registry.

For example, currently `hauler store copy registry://<registry>` takes credentials for authentication but `hauler store add image` and `hauler store sync` are missing that option.  So running `docker/cosign login` prior to those commands are the workaround until we get this handled totally by Hauler.
