### ISSUE TITLE
[feature]  when use `hauler store copy `, Run `hauler store info`, The copied image should be displayed 

### ISSUE THREAD

**Issue by Miaoxiang-philips** [hauler-dev/hauler#285]
Hey Team !

We used  `hauler store serve registry` to start my image registry on `A`

And then, We need to upload image  externally to this registry,

So we do it:
1. at another Linux Server `B`, Run `hauler store pull my_image:tag`
2. Run `hauler store copy registry://target_hauler_registry_server:port`

it works, but when i use `hauler store info` on `A`, i can't find my uploaded image, but it can use `docker pull A_IP:port/my_image:tag`  to pull image

![image](https://github.com/user-attachments/assets/6138fcbe-51ef-4d34-8650-ec1d80b4317e)

I'm not sure if this conflicts with the goal of hauler. My understanding is that since it is possible to upload(hauler copy) images, it should provide a view of the list of all images

**Describe Proposed Solution(s):**

- 

**Describe Possible Alternatives:**

- I can indeed find the image I uploaded in the hauler `registry/` metadata information, But it's not friendly

**Additional Context:**

-

**Comment by zackbradys** [comment]
Hey @Miaoxiang-philips, it looks like you accidentally used `hauler store pull my_image:tag`, when it should be `hauler store add image my_image:tag`. 

You are able to `docker push` to the registry, but we don't recommend it, because artifacts won't be added to the `store`. It might be useful to check out the quickstart guide! --> https://rancherfederal.github.io/hauler-docs/docs/introduction/quickstart

**Comment by dweomer** [comment]
> You are able to `docker push` to the registry, but we don't recommend it, because artifacts won't be added to the `store`.

We have no plans at this time to support collecting images into the store via push.
