### ISSUE TITLE
[feature] sync or push should continue after error

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#296]
**Is this RFE related to an Existing Problem? If so, please describe:**

Customer is asking for the hauler sync or push functions continue after an error. Specifically from image pull that didn't work they want hauler to try and complete the rest of the list. 

-

**Describe Proposed Solution(s):**

Have a flag that will try every item in the manifest. 
-

**Describe Possible Alternatives:**

Retrying the sync/push until the one item completes. 
-

**Additional Context:**

-

**Comment by zackbradys** [comment]
Similar issue to Issue https://github.com/hauler-dev/hauler/issues/284!

**Comment by ethanchowell** [comment]
It's not so much the image pull or retries that are causing issues as it is the behavior when you try to `hauler store copy` to a registry with tag immutability configured. In those cases if one of N number of images exists in the target registry, hauler exits at that first failure leaving some number of images unable to push.

**Comment by zackbradys** [comment]
Hey @ethanchowell... thanks for the additional information. We were discussing this a bit today and will continue to investigate how to address it. ECR is always tricky to work with...

**Comment by zackbradys** [comment]
Hey @clemenko / @ethanchowell, we resolved one of the issues of continuing on error and maintaining the amount of retries, defaulted at three retries, with PR https://github.com/hauler-dev/hauler/pull/317 and [v1.0.8](https://github.com/hauler-dev/hauler/releases/tag/v1.0.8), but will keep this open as an Issue/RFE due to the fact we still need to address tag immutability.

**Comment by ethanchowell** [comment]
I just tested 1.0.8 and I'm still observing the issue where when I run `hauler store copy registry://<dest>`, if one image fails, execution stops and no other images push. This isn't really related to ecr and it's mechanics around tag mutability, I only used that as an example because it's an easy one to validate. The bigger issue is that if I rely on hauler to an airgapped environment and try to upload those images, I'm dead in the water if one of those image uploads fails because the registry I'm pushing to doesn't allow overwriting images they already have. Looks like it's a result of the bulk write failing [here](https://github.com/hauler-dev/cosign/blob/632f7026aeee1c4b2d492a87e062cec3027a8b16/pkg/oci/remote/write.go#L162)

**Comment by zackbradys** [comment]
partially similar to https://github.com/hauler-dev/hauler/issues/323 and linked others...

**Comment by CamrynCarter** [comment]
Closing in favor of https://github.com/hauler-dev/hauler/pull/368 (option for continue on error)

**Comment by zackbradys** [comment]
for awareness... tracking the second part of this enhance in Issue https://github.com/hauler-dev/hauler/issues/284!
