### ISSUE TITLE
[feature] Minimal version of Manifest for bootstraping NEW POCs

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#306]
IHAC that is looking to use Hauler to bootstrap new clusters. They are worried about the time and disk space required when using `hauler store sync --platforms....`

-

Current `hauler store sync --platforms....` can exceed 40gb. They are looking for the minimal. 

-

Creating a "--minimal" flag to ONLY sync the specific version and not all the versions. It would also be nice to have a template option for displaying what will be downloaded before downloading. 

-

**Additional Context:**

-

**Comment by zackbradys** [comment]
Closing due to the fact that we would need upstream Rancher or Rancher Government to officially release a minified version of images for any of our products before implementing this feature.

---

Users are able to build and `hauler store sync` their own manifests today. If they are unsure of how to build manifests, there are a few example in the docs: https://docs.hauler.dev/docs/guides-references/manifests

If Carbide Customers are looking to inspect the existing manifests that are used when using `hauler store sync --products strings`... here is one way to inspect them:

```bash
hauler store add image rgcrprod.azurecr.us/hauler/rke2-manifest.yaml:v1.28.12-rke2r1
2024-08-26 10:00:21 INF adding 'image' [rgcrprod.azurecr.us/hauler/rke2-manifest.yaml:v1.28.12-rke2r1] to the store
2024-08-26 10:00:24 INF successfully added 'image' [rgcrprod.azurecr.us/hauler/rke2-manifest.yaml:v1.28.12-rke2r1]

zackbradys@Zacks-MBP Downloads % hauler store info
+-------------------------------------------+-------+----------+----------+--------+
| REFERENCE                                 | TYPE  | PLATFORM | # LAYERS | SIZE   |
+-------------------------------------------+-------+----------+----------+--------+
| hauler/rke2-manifest.yaml:v1.28.12-rke2r1 | image | -        |        1 | 5.7 kB |
|                                           | atts  | -        |        1 | 1.8 kB |
+-------------------------------------------+-------+----------+----------+--------+
|                                                                 TOTAL   | 7.4 KB |
+-------------------------------------------+-------+----------+----------+--------+

hauler store extract hauler/rke2-manifest.yaml:v1.28.12-rke2r1 | cat rke2-manifest.yaml
```

**Comment by clemenko** [comment]
understood. guess I will have to bash this.
