### ISSUE TITLE
`hauler store copy` to `hauler store server` working as expected?

### ISSUE THREAD

**Issue by Miaoxiang-philips** [hauler-dev/hauler#316]
Hi there,

As stated in the title, I execute `hauler store serve registry` on Server A, and I have a hauler store on Server B. I then ran `hauler store copy registry://A_Server_IP:5000` on Server B to transfer images. Is this behavior expected?

If it is expected, how can I delete some of the images that were transferred by `hauler store copy` on Server A?

**Comment by zackbradys** [comment]
Hey @Miaoxiang-philips, I'm not sure your use case for using `hauler store copy` from one `store` to another `store`, but adding or removing images directly from the `registry` is not supported since it doesn't update the `store` so your `registry` and `store` would be out of sync.

Typically, we recommend users `hauler store save` on one server, move the `tar.zst` to another server (aka airgap the tarball), and then `hauler store load` on the other server.
